"""Regenerate D/A/S scores and Mental_Health_Status for the tabular dataset
from a designed, plausible relationship to the 18 real feature columns, so
the fusion/classifier/regressor models have something genuine to learn.

    python training/generate_synthetic_labels.py

WHY THIS EXISTS: dataset/mental_health_multimodal.csv's original labels were
verified (docs/model_placement.md) to carry no statistical relationship to
its 18 feature columns -- linear correlation and a random forest both landed
at/below trivial baselines. That's a property of this specific file, not
something a model can fix by training harder.

WHAT THIS SCRIPT DOES: keeps the 18 feature columns exactly as-is, and
replaces Depression_Score / Anxiety_Score / Stress_Score / Mental_Health_Status
with values generated by backend.core.inference's own heuristic formulas
(estimate_scores / classify_status -- the same domain-knowledge weights the
app already uses, e.g. worse sleep -> more depression, higher GSR/lower HRV
-> more anxiety) plus Gaussian noise, so there IS a learnable-but-imperfect
relationship, similar in spirit to how a real questionnaire-based ground
truth would relate to these features: mostly explained by them, not perfectly.

THIS IS NOT REAL CLINICAL GROUND TRUTH. It's a designed relationship for
training/demo purposes, output to a separate file
(dataset/mental_health_multimodal_synthetic_labels.csv) so the original data
is never overwritten and nobody can mistake the regenerated labels for
validated psychological measurements. Models trained on it demonstrate that
the pipeline can learn a real relationship when one exists -- they do not
carry clinical predictive validity.
"""

import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from backend.core.dataset_spec import FEATURE_STATS, NUMERICAL_FEATURE_KEYS, SCORE_MAX, STATUS_LABELS  # noqa: E402
from backend.core.inference.regression_engine import estimate_scores  # noqa: E402

SRC_PATH = ROOT / "dataset" / "mental_health_multimodal.csv"
OUT_PATH = ROOT / "dataset" / "mental_health_multimodal_synthetic_labels.csv"

# Noise as a fraction of each score's valid range -- enough that the relationship
# isn't perfectly deterministic (a real screening signal never is), but small
# enough that it stays clearly learnable.
NOISE_FRAC = 0.12
SEED = 42

# Target status proportions for a plausible general screening population
# (most people screen healthy; severe is rare) -- roughly matching the
# original file's Healthy/Mild/Moderate/Severe shape. classify_status()'s
# built-in thresholds were tuned for a different assumption (a "mild by
# default" baseline) and produced a Mild/Moderate-heavy distribution instead,
# so status here uses quantile cutoffs on burden fit to this target shape.
TARGET_STATUS_PROPORTIONS = {"Healthy": 0.40, "Mild_Stress": 0.31, "Moderate_Stress": 0.25, "Severe_Stress": 0.04}


def main():
    df = pd.read_csv(SRC_PATH)
    rng = np.random.default_rng(SEED)

    dep, anx, strs, burdens = [], [], [], []
    for _, row in df.iterrows():
        z = np.array(
            [(row[k] - FEATURE_STATS[k][0]) / (FEATURE_STATS[k][1] + 1e-8) for k in NUMERICAL_FEATURE_KEYS],
            dtype=np.float32,
        )
        scores = estimate_scores(z, np.array([]), np.array([]))
        noisy = {
            name: float(np.clip(val + rng.normal(0, NOISE_FRAC * SCORE_MAX[name]), 0, SCORE_MAX[name]))
            for name, val in scores.items()
        }
        dep.append(noisy["depression"])
        anx.append(noisy["anxiety"])
        strs.append(noisy["stress"])
        burdens.append(0.4 * noisy["depression"] / SCORE_MAX["depression"] + 0.3 * noisy["anxiety"] / SCORE_MAX["anxiety"] + 0.3 * noisy["stress"] / SCORE_MAX["stress"])

    burdens = np.array(burdens)
    cum = np.cumsum([TARGET_STATUS_PROPORTIONS[s] for s in STATUS_LABELS])
    cutoffs = np.quantile(burdens, cum[:-1])
    status_idx = np.searchsorted(cutoffs, burdens, side="right")
    status = [STATUS_LABELS[i] for i in status_idx]

    out = df.copy()
    out["Depression_Score"] = np.round(dep, 1)
    out["Anxiety_Score"] = np.round(anx, 1)
    out["Stress_Score"] = np.round(strs, 1)
    out["Mental_Health_Status"] = status

    out.to_csv(OUT_PATH, index=False)
    print(f"wrote {OUT_PATH} ({len(out)} rows)")
    print("\nnew status distribution:")
    print(out["Mental_Health_Status"].value_counts())
    print("\nscore ranges:")
    print(out[["Depression_Score", "Anxiety_Score", "Stress_Score"]].describe())


if __name__ == "__main__":
    main()
